dev.new()
data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?", colClasses=c("character","character",rep("numeric",7)))
data$DateTime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
dataToPlot <- data[as.Date(data$DateTime) >= "2007-02-01" & as.Date(data$DateTime) <= "2007-02-02",]
par(mfrow = c(2,2), mar = c(4, 4, 4, 1))
with(dataToPlot, plot(DateTime, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power"))
with(dataToPlot, plot(DateTime, Voltage, type = "l", xlab = "datetime", ylab = "Voltage"))
with(dataToPlot, plot(DateTime, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering"))
with(dataToPlot, lines(DateTime, Sub_metering_2, col = "red"))
with(dataToPlot, lines(DateTime, Sub_metering_3, col = "blue"))
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, bty = "n", col = c("black", "red", "blue"))
with(dataToPlot, plot(DateTime, Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power"))
dev.copy(png, file = "plot4.png", width = 480, height = 480)
dev.off()